version: "3.8"
services:
    api:
        container_name: go_commerce_api
        build:
            context: ./
        environment:
            APP_DEBUG: "${APP_DEBUG}"
        ports:
            - "80:${APP_PORT}"
        volumes:
            - "./:/go/src/api/"
        networks:
            - go_commerce_network

    database:
        container_name: go_commerce_mysql
        image: mysql
        ports:
            - "${DATABASE_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
            MYSQL_DATABASE: "${DATABASE_NAME}"
        networks:
            - go_commerce_network
networks:
    go_commerce_network:
        driver: bridge
