// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/leeliwei930/go_commerce/ent/paymentchannel"
)

// PaymentChannel is the model entity for the PaymentChannel schema.
type PaymentChannel struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentChannel) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentchannel.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type PaymentChannel", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentChannel fields.
func (pc *PaymentChannel) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentchannel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pc.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this PaymentChannel.
// Note that you need to call PaymentChannel.Unwrap() before calling this method if this PaymentChannel
// was returned from a transaction, and the transaction was committed or rolled back.
func (pc *PaymentChannel) Update() *PaymentChannelUpdateOne {
	return (&PaymentChannelClient{config: pc.config}).UpdateOne(pc)
}

// Unwrap unwraps the PaymentChannel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pc *PaymentChannel) Unwrap() *PaymentChannel {
	tx, ok := pc.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentChannel is not a transactional entity")
	}
	pc.config.driver = tx.drv
	return pc
}

// String implements the fmt.Stringer.
func (pc *PaymentChannel) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentChannel(")
	builder.WriteString(fmt.Sprintf("id=%v", pc.ID))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentChannels is a parsable slice of PaymentChannel.
type PaymentChannels []*PaymentChannel

func (pc PaymentChannels) config(cfg config) {
	for _i := range pc {
		pc[_i].config = cfg
	}
}
