// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/leeliwei930/go_commerce/ent/paymentmethod"
	"github.com/leeliwei930/go_commerce/ent/predicate"
)

// PaymentMethodQuery is the builder for querying PaymentMethod entities.
type PaymentMethodQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.PaymentMethod
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PaymentMethodQuery builder.
func (pmq *PaymentMethodQuery) Where(ps ...predicate.PaymentMethod) *PaymentMethodQuery {
	pmq.predicates = append(pmq.predicates, ps...)
	return pmq
}

// Limit adds a limit step to the query.
func (pmq *PaymentMethodQuery) Limit(limit int) *PaymentMethodQuery {
	pmq.limit = &limit
	return pmq
}

// Offset adds an offset step to the query.
func (pmq *PaymentMethodQuery) Offset(offset int) *PaymentMethodQuery {
	pmq.offset = &offset
	return pmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pmq *PaymentMethodQuery) Unique(unique bool) *PaymentMethodQuery {
	pmq.unique = &unique
	return pmq
}

// Order adds an order step to the query.
func (pmq *PaymentMethodQuery) Order(o ...OrderFunc) *PaymentMethodQuery {
	pmq.order = append(pmq.order, o...)
	return pmq
}

// First returns the first PaymentMethod entity from the query.
// Returns a *NotFoundError when no PaymentMethod was found.
func (pmq *PaymentMethodQuery) First(ctx context.Context) (*PaymentMethod, error) {
	nodes, err := pmq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{paymentmethod.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pmq *PaymentMethodQuery) FirstX(ctx context.Context) *PaymentMethod {
	node, err := pmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PaymentMethod ID from the query.
// Returns a *NotFoundError when no PaymentMethod ID was found.
func (pmq *PaymentMethodQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pmq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{paymentmethod.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pmq *PaymentMethodQuery) FirstIDX(ctx context.Context) int {
	id, err := pmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PaymentMethod entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one PaymentMethod entity is not found.
// Returns a *NotFoundError when no PaymentMethod entities are found.
func (pmq *PaymentMethodQuery) Only(ctx context.Context) (*PaymentMethod, error) {
	nodes, err := pmq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{paymentmethod.Label}
	default:
		return nil, &NotSingularError{paymentmethod.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pmq *PaymentMethodQuery) OnlyX(ctx context.Context) *PaymentMethod {
	node, err := pmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PaymentMethod ID in the query.
// Returns a *NotSingularError when exactly one PaymentMethod ID is not found.
// Returns a *NotFoundError when no entities are found.
func (pmq *PaymentMethodQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pmq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{paymentmethod.Label}
	default:
		err = &NotSingularError{paymentmethod.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pmq *PaymentMethodQuery) OnlyIDX(ctx context.Context) int {
	id, err := pmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PaymentMethods.
func (pmq *PaymentMethodQuery) All(ctx context.Context) ([]*PaymentMethod, error) {
	if err := pmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pmq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pmq *PaymentMethodQuery) AllX(ctx context.Context) []*PaymentMethod {
	nodes, err := pmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PaymentMethod IDs.
func (pmq *PaymentMethodQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := pmq.Select(paymentmethod.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pmq *PaymentMethodQuery) IDsX(ctx context.Context) []int {
	ids, err := pmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pmq *PaymentMethodQuery) Count(ctx context.Context) (int, error) {
	if err := pmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pmq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pmq *PaymentMethodQuery) CountX(ctx context.Context) int {
	count, err := pmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pmq *PaymentMethodQuery) Exist(ctx context.Context) (bool, error) {
	if err := pmq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pmq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pmq *PaymentMethodQuery) ExistX(ctx context.Context) bool {
	exist, err := pmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PaymentMethodQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pmq *PaymentMethodQuery) Clone() *PaymentMethodQuery {
	if pmq == nil {
		return nil
	}
	return &PaymentMethodQuery{
		config:     pmq.config,
		limit:      pmq.limit,
		offset:     pmq.offset,
		order:      append([]OrderFunc{}, pmq.order...),
		predicates: append([]predicate.PaymentMethod{}, pmq.predicates...),
		// clone intermediate query.
		sql:  pmq.sql.Clone(),
		path: pmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (pmq *PaymentMethodQuery) GroupBy(field string, fields ...string) *PaymentMethodGroupBy {
	group := &PaymentMethodGroupBy{config: pmq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pmq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (pmq *PaymentMethodQuery) Select(fields ...string) *PaymentMethodSelect {
	pmq.fields = append(pmq.fields, fields...)
	return &PaymentMethodSelect{PaymentMethodQuery: pmq}
}

func (pmq *PaymentMethodQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pmq.fields {
		if !paymentmethod.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pmq.path != nil {
		prev, err := pmq.path(ctx)
		if err != nil {
			return err
		}
		pmq.sql = prev
	}
	return nil
}

func (pmq *PaymentMethodQuery) sqlAll(ctx context.Context) ([]*PaymentMethod, error) {
	var (
		nodes = []*PaymentMethod{}
		_spec = pmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &PaymentMethod{config: pmq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, pmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pmq *PaymentMethodQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pmq.querySpec()
	return sqlgraph.CountNodes(ctx, pmq.driver, _spec)
}

func (pmq *PaymentMethodQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := pmq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (pmq *PaymentMethodQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   paymentmethod.Table,
			Columns: paymentmethod.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: paymentmethod.FieldID,
			},
		},
		From:   pmq.sql,
		Unique: true,
	}
	if unique := pmq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := pmq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentmethod.FieldID)
		for i := range fields {
			if fields[i] != paymentmethod.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pmq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pmq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pmq *PaymentMethodQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pmq.driver.Dialect())
	t1 := builder.Table(paymentmethod.Table)
	columns := pmq.fields
	if len(columns) == 0 {
		columns = paymentmethod.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pmq.sql != nil {
		selector = pmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range pmq.predicates {
		p(selector)
	}
	for _, p := range pmq.order {
		p(selector)
	}
	if offset := pmq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pmq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PaymentMethodGroupBy is the group-by builder for PaymentMethod entities.
type PaymentMethodGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pmgb *PaymentMethodGroupBy) Aggregate(fns ...AggregateFunc) *PaymentMethodGroupBy {
	pmgb.fns = append(pmgb.fns, fns...)
	return pmgb
}

// Scan applies the group-by query and scans the result into the given value.
func (pmgb *PaymentMethodGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pmgb.path(ctx)
	if err != nil {
		return err
	}
	pmgb.sql = query
	return pmgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pmgb *PaymentMethodGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pmgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PaymentMethodGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pmgb.fields) > 1 {
		return nil, errors.New("ent: PaymentMethodGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pmgb *PaymentMethodGroupBy) StringsX(ctx context.Context) []string {
	v, err := pmgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PaymentMethodGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pmgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{paymentmethod.Label}
	default:
		err = fmt.Errorf("ent: PaymentMethodGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pmgb *PaymentMethodGroupBy) StringX(ctx context.Context) string {
	v, err := pmgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PaymentMethodGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pmgb.fields) > 1 {
		return nil, errors.New("ent: PaymentMethodGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pmgb *PaymentMethodGroupBy) IntsX(ctx context.Context) []int {
	v, err := pmgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PaymentMethodGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pmgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{paymentmethod.Label}
	default:
		err = fmt.Errorf("ent: PaymentMethodGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pmgb *PaymentMethodGroupBy) IntX(ctx context.Context) int {
	v, err := pmgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PaymentMethodGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pmgb.fields) > 1 {
		return nil, errors.New("ent: PaymentMethodGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pmgb *PaymentMethodGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pmgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PaymentMethodGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pmgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{paymentmethod.Label}
	default:
		err = fmt.Errorf("ent: PaymentMethodGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pmgb *PaymentMethodGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pmgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PaymentMethodGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pmgb.fields) > 1 {
		return nil, errors.New("ent: PaymentMethodGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pmgb *PaymentMethodGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pmgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PaymentMethodGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pmgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{paymentmethod.Label}
	default:
		err = fmt.Errorf("ent: PaymentMethodGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pmgb *PaymentMethodGroupBy) BoolX(ctx context.Context) bool {
	v, err := pmgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pmgb *PaymentMethodGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pmgb.fields {
		if !paymentmethod.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pmgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pmgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pmgb *PaymentMethodGroupBy) sqlQuery() *sql.Selector {
	selector := pmgb.sql.Select()
	aggregation := make([]string, 0, len(pmgb.fns))
	for _, fn := range pmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pmgb.fields)+len(pmgb.fns))
		for _, f := range pmgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pmgb.fields...)...)
}

// PaymentMethodSelect is the builder for selecting fields of PaymentMethod entities.
type PaymentMethodSelect struct {
	*PaymentMethodQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pms *PaymentMethodSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pms.prepareQuery(ctx); err != nil {
		return err
	}
	pms.sql = pms.PaymentMethodQuery.sqlQuery(ctx)
	return pms.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pms *PaymentMethodSelect) ScanX(ctx context.Context, v interface{}) {
	if err := pms.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (pms *PaymentMethodSelect) Strings(ctx context.Context) ([]string, error) {
	if len(pms.fields) > 1 {
		return nil, errors.New("ent: PaymentMethodSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := pms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pms *PaymentMethodSelect) StringsX(ctx context.Context) []string {
	v, err := pms.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (pms *PaymentMethodSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pms.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{paymentmethod.Label}
	default:
		err = fmt.Errorf("ent: PaymentMethodSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pms *PaymentMethodSelect) StringX(ctx context.Context) string {
	v, err := pms.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (pms *PaymentMethodSelect) Ints(ctx context.Context) ([]int, error) {
	if len(pms.fields) > 1 {
		return nil, errors.New("ent: PaymentMethodSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := pms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pms *PaymentMethodSelect) IntsX(ctx context.Context) []int {
	v, err := pms.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (pms *PaymentMethodSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pms.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{paymentmethod.Label}
	default:
		err = fmt.Errorf("ent: PaymentMethodSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pms *PaymentMethodSelect) IntX(ctx context.Context) int {
	v, err := pms.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (pms *PaymentMethodSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(pms.fields) > 1 {
		return nil, errors.New("ent: PaymentMethodSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := pms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pms *PaymentMethodSelect) Float64sX(ctx context.Context) []float64 {
	v, err := pms.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (pms *PaymentMethodSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pms.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{paymentmethod.Label}
	default:
		err = fmt.Errorf("ent: PaymentMethodSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pms *PaymentMethodSelect) Float64X(ctx context.Context) float64 {
	v, err := pms.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (pms *PaymentMethodSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(pms.fields) > 1 {
		return nil, errors.New("ent: PaymentMethodSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := pms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pms *PaymentMethodSelect) BoolsX(ctx context.Context) []bool {
	v, err := pms.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (pms *PaymentMethodSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pms.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{paymentmethod.Label}
	default:
		err = fmt.Errorf("ent: PaymentMethodSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pms *PaymentMethodSelect) BoolX(ctx context.Context) bool {
	v, err := pms.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pms *PaymentMethodSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pms.sql.Query()
	if err := pms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
