// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/leeliwei930/go_commerce/ent/brand"
	"github.com/leeliwei930/go_commerce/ent/product"
	"github.com/leeliwei930/go_commerce/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	brandFields := schema.Brand{}.Fields()
	_ = brandFields
	// brandDescIsActive is the schema descriptor for is_active field.
	brandDescIsActive := brandFields[3].Descriptor()
	// brand.DefaultIsActive holds the default value on creation for the is_active field.
	brand.DefaultIsActive = brandDescIsActive.Default.(bool)
	// brandDescCreatedAt is the schema descriptor for created_at field.
	brandDescCreatedAt := brandFields[5].Descriptor()
	// brand.DefaultCreatedAt holds the default value on creation for the created_at field.
	brand.DefaultCreatedAt = brandDescCreatedAt.Default.(func() time.Time)
	// brandDescUpdatedAt is the schema descriptor for updated_at field.
	brandDescUpdatedAt := brandFields[6].Descriptor()
	// brand.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	brand.DefaultUpdatedAt = brandDescUpdatedAt.Default.(func() time.Time)
	// brandDescID is the schema descriptor for id field.
	brandDescID := brandFields[0].Descriptor()
	// brand.DefaultID holds the default value on creation for the id field.
	brand.DefaultID = brandDescID.Default.(func() uuid.UUID)
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescName is the schema descriptor for name field.
	productDescName := productFields[1].Descriptor()
	// product.NameValidator is a validator for the "name" field. It is called by the builders before save.
	product.NameValidator = productDescName.Validators[0].(func(string) error)
	// productDescIsActive is the schema descriptor for is_active field.
	productDescIsActive := productFields[3].Descriptor()
	// product.DefaultIsActive holds the default value on creation for the is_active field.
	product.DefaultIsActive = productDescIsActive.Default.(bool)
	// productDescPublishedAt is the schema descriptor for published_at field.
	productDescPublishedAt := productFields[4].Descriptor()
	// product.PublishedAtValidator is a validator for the "published_at" field. It is called by the builders before save.
	product.PublishedAtValidator = productDescPublishedAt.Validators[0].(func(string) error)
	// productDescCreatedAt is the schema descriptor for created_at field.
	productDescCreatedAt := productFields[5].Descriptor()
	// product.DefaultCreatedAt holds the default value on creation for the created_at field.
	product.DefaultCreatedAt = productDescCreatedAt.Default.(func() time.Time)
	// productDescUpdatedAt is the schema descriptor for updated_at field.
	productDescUpdatedAt := productFields[6].Descriptor()
	// product.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	product.DefaultUpdatedAt = productDescUpdatedAt.Default.(func() time.Time)
	// productDescID is the schema descriptor for id field.
	productDescID := productFields[0].Descriptor()
	// product.DefaultID holds the default value on creation for the id field.
	product.DefaultID = productDescID.Default.(func() uuid.UUID)
}
