// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Brand is the predicate function for brand builders.
type Brand func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Inventory is the predicate function for inventory builders.
type Inventory func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// PaymentChannel is the predicate function for paymentchannel builders.
type PaymentChannel func(*sql.Selector)

// PaymentMethod is the predicate function for paymentmethod builders.
type PaymentMethod func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
